sudo: false
language: java
jdk:
- oraclejdk8
before_script:
- mkdir -p ext
- wget http://iweb.dl.sourceforge.net/project/launch4j/launch4j-3/3.8/launch4j-3.8-linux.tgz
- echo "e0cb0240c91b3ed6ca7bb85743fd09d6d7651cc3671a5fc17f67e57b8f7a80c6  launch4j-3.8-linux.tgz" | sha256sum -c
- tar -C ext -xzf launch4j-3.8-linux.tgz
- ant fetch

script: ant windist
env:
  global:
    secure: Df5FIHnieDJj8AAwgeAh779Rs+aoJ8e9WQN0ero4OfcJ2Y1G7InBZQIGesfVR1M7EX4Hf0fvmUam9zthdwi4culk+gJeOAMM/wpCqvEUyWDTd78Cr08L7PjNW8RCq5NCYhgvO1j+IzJOA3IR6h8DSS4QGZtJqPYk65ZQ1uRyAGc=
addons:
  coverity_scan:
    project:
      name: martinpaljak/esteidhacker
    notification_email: martin@martinpaljak.net
    build_command: ant compile
    branch_pattern: coverity
deploy:
  provider: releases
  file:
  - esteid.jar
  - esteid-app.jar
  - esteid.exe
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: nyJNh410mWIAGdLXRQA6/TFByEjRdxk4i3sXIDBTYD3jcmgEp2BYTSi3gSMaOoNgGl2KH4VgvnT48eJrvZssF39PT4h/36SCmtOfhdWVExwJDbVSY22o24brp7VjbkN2/wAl1qF/yRKEdWF3Xkc3abzpSx27aoRS8nDEvKB5v1M=

cache:
  directories:
    - lib
    - ext
